name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Verify files
      run: |
        ls -la
        if [ -f "index.html" ]; then
          echo "Main files exist"
        else
          echo "ERROR: Missing index.html"
          exit 1
        fi

    - name: Prepare project
      run: |
        mkdir -p app/src/main/assets/www
        cp *.html *.css *.js app/src/main/assets/www/ || echo "No HTML/CSS/JS files"
        
        if [ -d "assets" ]; then
          mkdir -p app/src/main/assets/www/assets
          cp -r assets/* app/src/main/assets/www/assets/ || echo "No assets copied"
        fi

    - name: Setup Android SDK
      run: |
        yes | sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0"
        echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV

    - name: Build APK
      run: |
        chmod +x gradlew
        ./gradlew assembleDebug --stacktrace --info

    - name: Upload APK
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
    
